baseURL = 'https://notes.frlab.eu/'
languageCode = 'en-us'
title = 'frlab::notes'
theme = 'hugo-book'



[security]
enableInlineShortcodes = false

[security.exec]
allow = ['^((dart-)?sass(-embedded)?|go|npx|postcss|asciidoctor)$']
osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|HOME|TMP|TEMP|TERM)$']

[security.funcs]
getenv = ['^(HUGO_|REPOSITORY_URL|^BRANCH$)']

[security.goTemplates]
allowActionJSTmpl = false

[security.http]
methods = ['(?i)GET|POST']
urls = ['.*']
